config/routes.rb
SurveyApp::Application.routes.draw do

  root :to => "surveys#index"

  resources :surveys, :only => [:index, :show, :edit, :update]
  resources :survey_submissions, :only => [:create]

  get "thanks" => "static_pages#thanks"
  get "error" => "static_pages#error"

end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id         :integer          not null, primary key
#  survey_id  :integer
#  label      :string(255)
#  position   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Question < ActiveRecord::Base
  attr_accessible :label, :position, :survey_id
  default_scope order("position")

  belongs_to :survey

  has_many :user_responses, 
    :class_name => "QuestionResponse", 
    :foreign_key => :question_id

  has_many :users_responded, 
    :through => :user_responses, 
    :source => :user

end

app/models/question_response.rb
# == Schema Information
#
# Table name: question_responses
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  question_id :integer
#  response    :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class QuestionResponse < ActiveRecord::Base
  attr_accessible :user_id, :question_id, :response

  belongs_to :user
  belongs_to :question
  has_one :survey, :through => :question

end

app/models/survey.rb
# == Schema Information
#
# Table name: surveys
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Survey < ActiveRecord::Base
  attr_accessible :name, :questions_attributes

  has_many :questions
  has_many :user_responses, :through => :questions
  has_many :users_responded, :through => :questions, :uniq => true

  accepts_nested_attributes_for :questions

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  email      :string(255)
#  ip_address :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :email, :ip_address, :responses_attributes

  has_many :responses, 
    :class_name => "QuestionResponse",
    :foreign_key => :user_id

  has_many :surveys_completed,
    :through => :responses, 
    :source => :survey,
    :uniq => true

  accepts_nested_attributes_for :responses

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def thanks
  end

  def error
  end

end

app/controllers/survey_submissions_controller.rb
class SurveySubmissionsController < ApplicationController

  def create
    user = User.where(email: params[:user][:email]).first_or_create
    user.responses_attributes = params[:user][:responses_attributes]
    if user.save
      redirect_to thanks_url
    else
      redirect_to error_url
    end
  end

end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController

  def index
    @surveys = Survey.all
  end

  def show
    @survey = Survey.includes(:questions).find(params[:id])
  end

  def edit
    @survey = Survey.includes(:questions).find(params[:id])
  end

  def update
    survey = Survey.find(params[:id])
    if survey.update_attributes(params[:survey])
      redirect_to survey_url(survey)
    else
      redirect_to edit_survey_url(survey)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/survey_submissions_helper.rb
module SurveySubmissionsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SurveyApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="content">
  <%= yield %>
</div>

</body>
</html>

app/views/static_pages/error.html.erb
<h2>Oops!</h2>
<h3>There was a problem. Please try again.</h3>

app/views/static_pages/thanks.html.erb
<h2>Thanks!</h2>
<h3>Your survey has been saved.</h3>

<%= link_to "Take another survey", surveys_url  %>

app/views/surveys/edit.html.erb
<span>
  <%= link_to "Surveys", surveys_url  %> > 
  <%= link_to @survey.name, survey_url(@survey) %> > Edit
</span>

<p></p>

<form action="<%= survey_url(@survey) %>" method="post">
  <input type="hidden" name="_method" value="put" />
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />

  <h3>Survey:</h3>

  <label for="survey_name">Name:</label>
  <input type="text" name="survey[name]" value="<%= @survey.name %>" />

  <h3>Questions:</h3>
  <ul class="questions">
  <% @survey.questions.each do |question| %>
    <li class="question">
      <input type="hidden"
             name="survey[questions_attributes][<%= question.id %>][id]"
             value="<%= question.id %>" />
      <input type="hidden"
             name="survey[questions_attributes][<%= question.id %>][position]"
             value="<%= question.position %>" />
      <input type="text"
             id="question_<%= question.id %>" 
             name="survey[questions_attributes][<%= question.id %>][label]"
             value="<%= question.label %>"
             />
    </li>
  <% end %>
  </ul>

  <input type="submit" value="Save Survey" />
</form>

<script type="text/javascript">
$(function () {
  $('.questions').sortable({
    axis: 'y',

    start: function (e, ui) {
      ui.placeholder.width(ui.item.width());
      ui.placeholder.height(ui.item.height());
    },    

    update: function (date) {
      items: "p.question",
      sortData = $(this).sortable("serialize");
      console.log(sortData);
    },

    sort: function (event, ui) {
      var that = $(this),
      w = ui.helper.outerHeight();
      that.children().each(function () {
        if ($(this).hasClass('ui-sortable-helper') || 
          $(this).hasClass('ui-sortable-placeholder')) {
          return true;          
        }
        // if overlap is more than half of the dragged item
        var dist = Math.abs(ui.position.left - $(this).position().top),
        before = ui.position.left > $(this).position().top;
        if ((w - dist) > (w / 2) && (dist < w)) {
          if (before) {
            $('.ui-sortable-placeholder', that).insertBefore($(this));            
          } else {
            $('.ui-sortable-placeholder', that).insertAfter($(this));            
          }
          return false;
        }
      });
    }
  });
});
</script>

app/views/surveys/index.html.erb
<span>
  Surveys > All
</span>

<h2>Surveys:</h2>
<ul>
<% @surveys.each do |survey| %>
  <li><%= link_to survey.name, survey_url(survey) %></li>  
<% end %>
</ul>

app/views/surveys/show.html.erb
<span>
  <%= link_to "Surveys", surveys_url  %> > <%= @survey.name %> 
  (<%= link_to "edit", edit_survey_url(@survey) %>)
</span>

<form action="<%= survey_submissions_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />

  <h2><%= @survey.name %></h2>

  <p>
    <label for="email">Email address:</label>
    <input type="text" id="email" name="user[email]" />
  </p>

  <h3>Survey Questions:</h3>
  <% @survey.questions.each do |question| %>
    <p class="question">
      <label for="question_<%= question.id %>">
        <%= question.label %>
      </label>
      <input type="hidden" 
             name="user[responses_attributes][<%= question.id %>][question_id]"
             value="<%= question.id %>" />
      <input type="text"
             id="question_<%= question.id %>" 
             name="user[responses_attributes][<%= question.id %>][response]"
             />
    </p>
  <% end %>

  <input type="submit" value="Save Survey" />
</form>